const SPIN_AND_WIN_GAME_TYPE = "Spin The Wheel";
const SCRATCH_CARD_GAME_TYPE = "Scratch Card";
const PICKUP_CARD_GAME_TYPE = "PickUpCard";
const CLAW_MACHINE_GAME_TYPE = "ClawMachine";
const BUBBLE_SHOOTER_GAME_TYPE = "BubbleShooter";
const GIFT_CATCHER_GAME_TYPE = "CatchingGame";

export {
  SCRATCH_CARD_GAME_TYPE,
  SPIN_AND_WIN_GAME_TYPE,
  PICKUP_CARD_GAME_TYPE,
  CLAW_MACHINE_GAME_TYPE,
  BUBBLE_SHOOTER_GAME_TYPE,
  GIFT_CATCHER_GAME_TYPE,
};
